### PR TITLE
add img tag loading='lazy' attribution for save bandwidth

### PR DESCRIPTION
**Pull request by kmvan**
Chrome81 tested and works.

### CODE REVIEW

**Comment by kmvan** [comment]
Link: #3

**Comment by kidonng** [comment]
You should add a polyfill (like https://github.com/mfranzke/loading-attribute-polyfill) to support browsers without native support with `loading="lazy"`.

**Comment by tim-soft** [comment]
@kmvan thanks for the PR! I'll look over this soon, I think lazyLoad should be an option that people can opt-out of. When you initially open the lightbox, does chrome load the prev/next image while on the current?

**Comment by tim-soft** [comment]
Great news! this feature has landed in https://github.com/tim-soft/react-spring-lightbox/pull/24 and available in v1.5.0

**Pull request closed without merging**
